#!/bin/sh
set -e

if [ "$1" = "configure" ]; then
    if command -v gtk-update-icon-cache >/dev/null 2>&1; then
        gtk-update-icon-cache -q /usr/share/icons/hicolor || true
    fi
fi


# Automatically added by dh_python3
if command -v py3compile >/dev/null 2>&1; then
	py3compile -p bodhi-update-manager /usr/lib/bodhi-update-manager
fi
if command -v pypy3compile >/dev/null 2>&1; then
	pypy3compile -p bodhi-update-manager /usr/lib/bodhi-update-manager || true
fi

# End automatically added section

